### ISSUE TITLE
Unique

### ISSUE THREAD

**Issue by paparyku** [Silksofthesoul/vue-m-validator#1]
A suggestion.

add a "unique" field that pings a http route (say laravel / express) and checks if a email/username/whatever is taken.

**Comment by Silksofthesoul** [comment]
Hello! In what form, would you like to transfer data to the server?

And...

how about this kind of function call?

```
      validator
        .addRule(RULE_1)
        .serverCheck({
          address: 'http://servername/validation',
          method: 'POST',
          data: {
             field1: 'usernameexample'
           }
        });
```

>> add a "unique" field that pings a http route

the plugin does not have "fields", in a conceptual form. You can independently send for validation the data that you need (and make them reactive if necessary), and set the verification rules on the client (please see the examples).

**Comment by Silksofthesoul** [comment]
@paparyku Hello! I update [package](https://www.npmjs.com/package/vue-m-validator) and [documentation.](https://github.com/Silksofthesoul/vue-m-validator/blob/master/README.md)
I hope the updated solution will be useful to you and other users (and maybe me 😃 )

For server communicate use 'serverCheck' method:
```
validator
  .addRule(RULE_1)
  .serverCheck(...see documentation...)
```

To use the new features, please update the package.
Run in commandline if you use npm:
`npm update vue-m-validator`
